/* 终端管理初始化脚本 */

-- 存储板块
INSERT INTO sys_bucket (bucket, name, storage, description) VALUES ('terminal.fota', 'FOTA升级', 'mongo_gridfs', 'FOTA升级文件存储板块');

-- 字典
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('commodu_type', '通信模组类型', '-', 9);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('cellular', '地面网', 'commodu_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('satellite', '卫星网', 'commodu_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('transport_type', '传输类型', '-', 10);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('report', '上报', 'transport_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('issued', '下发', 'transport_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('channel_type', '传输通道类型', '-', 11);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('cellular', '蜂窝网络', 'channel_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('satellite', '卫星网络', 'channel_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('fota_status', 'FOTA升级状态', '-', 12);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('ready', '准备', 'fota_status', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('process', '进行中', 'fota_status', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('over', '结束', 'fota_status', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('interrupt', '中断', 'fota_status', 4);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('asso_mode', 'FOTA关联模式', '-', 13);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('none', '无', 'asso_mode', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('mqtt', 'MQTT', 'asso_mode', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('iridium', '铱星', 'asso_mode', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('orbcomm', '海事', 'asso_mode', 4);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('gateway_type', '采集网关类型', '-', 14);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('mqtt', 'MQTT', 'gateway_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('coap', 'CoAP', 'gateway_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('socket', 'Socket', 'gateway_type', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('ecsat', '卫星平台', 'gateway_type', 4);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('iridium', '铱星', 'gateway_type', 5);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('orbcomm', '海事', 'gateway_type', 6);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('beidou', '北斗', 'gateway_type', 7);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('tiantong', '天通', 'gateway_type', 8);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('message_format', '报文格式', '-', 15);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('hex', '16进制', 'message_format', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('string', '字符串', 'message_format', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('base64', 'Base64', 'message_format', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('fota_order', 'FOTA指令', '-', 16);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('get_mate', '获取升级包元信息', 'fota_order', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('get_shard', '获取分片数据', 'fota_order', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('over', '升级包下载完成', 'fota_order', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('no_fota', '不需要升级', 'fota_order', 4);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('issued_mate', '发送升级包元信息', 'fota_order', 5);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('issued_shard', '发送升级包分片数据', 'fota_order', 6);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('no_mate', '无升级包元信息', 'fota_order', 7);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('no_shard', '无分片数据', 'fota_order', 8);

-- 功能
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0103', '终端管理', 'dir', '01', 'manager', 'el-icon-film', '#', NULL, 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010301', '终端类型', 'menu', '0103', 'manager', 'el-icon-office-building', '/terminal/type', NULL, 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030101', '查询', 'btn', '010301', 'manager', NULL, NULL, 'ter:type:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030102', '新增', 'btn', '010301', 'manager', NULL, NULL, 'ter:type:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030103', '修改', 'btn', '010301', 'manager', NULL, NULL, 'ter:type:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030104', '删除', 'btn', '010301', 'manager', NULL, NULL, 'ter:type:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010302', '终端信息', 'menu', '0103', 'manager', 'el-icon-office-building', '/terminal/info', NULL, 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030201', '查询', 'btn', '010302', 'manager', NULL, NULL, 'ter:info:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030202', '新增', 'btn', '010302', 'manager', NULL, NULL, 'ter:info:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030203', '修改', 'btn', '010302', 'manager', NULL, NULL, 'ter:info:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030204', '删除', 'btn', '010302', 'manager', NULL, NULL, 'ter:info:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030205', '绑定模组', 'btn', '010302', 'manager', NULL, NULL, 'ter:info:bind', 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030206', '导入', 'btn', '010302', 'manager', NULL, NULL, 'ter:info:imp', 6, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030207', '导出', 'btn', '010302', 'manager', NULL, NULL, 'ter:info:exp', 7, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030208', '报文下发', 'btn', '010302', 'manager', NULL, NULL, 'ter:info:issued', 8, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010303', 'FOTA升级', 'menu', '0103', 'manager', 'el-icon-office-building', '/terminal/fota', NULL, 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030301', '查询', 'btn', '010303', 'manager', NULL, NULL, 'ter:fota:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030302', '新增', 'btn', '010303', 'manager', NULL, NULL, 'ter:fota:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030303', '绑定终端', 'btn', '010303', 'manager', NULL, NULL, 'ter:fota:bind', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030304', '执行', 'btn', '010303', 'manager', NULL, NULL, 'ter:fota:exe', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030305', '中断', 'btn', '010303', 'manager', NULL, NULL, 'ter:fota:int', 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030306', '结束', 'btn', '010303', 'manager', NULL, NULL, 'ter:fota:over', 6, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030307', '删除', 'btn', '010303', 'manager', NULL, NULL, 'ter:fota:del', 7, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010304', '通信模组', 'menu', '0103', 'manager', 'el-icon-office-building', '/terminal/commodu', NULL, 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030401', '查询', 'btn', '010304', 'manager', NULL, NULL, 'ter:commodu:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030402', '新增', 'btn', '010304', 'manager', NULL, NULL, 'ter:commodu:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030403', '修改', 'btn', '010304', 'manager', NULL, NULL, 'ter:commodu:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030404', '删除', 'btn', '010304', 'manager', NULL, NULL, 'ter:commodu:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030405', '绑定终端', 'btn', '010304', 'manager', NULL, NULL, 'ter:commodu:bind', 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030406', '导入', 'btn', '010304', 'manager', NULL, NULL, 'ter:commodu:imp', 6, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030407', '导出', 'btn', '010304', 'manager', NULL, NULL, 'ter:commodu:exp', 7, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010305', '报文数据', 'menu', '0103', 'manager', 'el-icon-office-building', '/terminal/rawdata', NULL, 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030501', '查询', 'btn', '010305', 'manager', NULL, NULL, 'ter:rawdata:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030502', '导出', 'btn', '010305', 'manager', NULL, NULL, 'ter:rawdata:exp', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010306', '数据流量', 'menu', '0103', 'manager', 'el-icon-office-building', '/terminal/dataflow', NULL, 6, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030601', '查询', 'btn', '010306', 'manager', NULL, NULL, 'ter:dataflow:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030602', '导出', 'btn', '010306', 'manager', NULL, NULL, 'ter:dataflow:exp', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010307', '流量资费', 'menu', '0103', 'manager', 'el-icon-office-building', '/terminal/flowtariff', NULL, 7, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030701', '查询', 'btn', '010307', 'manager', NULL, NULL, 'ter:flowtariff:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030702', '新增', 'btn', '010307', 'manager', NULL, NULL, 'ter:flowtariff:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030703', '修改', 'btn', '010307', 'manager', NULL, NULL, 'ter:flowtariff:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030704', '删除', 'btn', '010307', 'manager', NULL, NULL, 'ter:flowtariff:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010308', '传输通道', 'menu', '0103', 'manager', 'el-icon-office-building', '/terminal/channel', NULL, 8, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030801', '查询', 'btn', '010308', 'manager', NULL, NULL, 'ter:channel:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030802', '新增', 'btn', '010308', 'manager', NULL, NULL, 'ter:channel:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030803', '修改', 'btn', '010308', 'manager', NULL, NULL, 'ter:channel:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01030804', '删除', 'btn', '010308', 'manager', NULL, NULL, 'ter:channel:del', 4, 1);

-- 传输通道
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cm_2g', '中国移动2G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cm_3g', '中国移动3G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cm_4g', '中国移动4G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cm_nb', '中国移动NB网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cm_bb', '中国移动带宽网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('ct_2g', '中国电信2G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('ct_3g', '中国电信3G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('ct_4g', '中国电信4G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('ct_nb', '中国电信NB网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('ct_bb', '中国电信带宽网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cu_2g', '中国联通2G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cu_3g', '中国联通3G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cu_4g', '中国联通4G网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cu_nb', '中国联通NB网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('cu_bb', '中国联通带宽网络', 'cellular');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('iridium', '铱星', 'satellite');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('orbcomm', '海事', 'satellite');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('beidou', '北斗', 'satellite');
INSERT INTO ter_channel (channel_id, channel_name, channel_type) VALUES ('tiantong', '天通', 'satellite');